"""empty message

Revision ID: 0a4387b829d7
Revises: dcc2f0c58b99
Create Date: 2016-04-26 16:19:09.309196

"""

# revision identifiers, used by Alembic.
revision = '0a4387b829d7'
down_revision = 'dcc2f0c58b99'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
   

def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass

